//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shop2StopDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_CUSTOMER
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_CUSTOMER()
        {
            this.tbl_CUSTOMER_ADDRESS = new HashSet<tbl_CUSTOMER_ADDRESS>();
            this.tbl_SPARE_INVOICE = new HashSet<tbl_SPARE_INVOICE>();
            this.tbl_SPARE_SALE_ORDER = new HashSet<tbl_SPARE_SALE_ORDER>();
        }
    
        public int CUSTOMER_ID { get; set; }
        public string CUST_NAME { get; set; }
        public Nullable<System.DateTime> DATE_OF_BIRTH { get; set; }
        public bool GENDER { get; set; }
        public Nullable<byte> CUST_TY_ID { get; set; }
        public string EMAIL_ADDRESS { get; set; }
        public Nullable<decimal> CREDIT_LIM { get; set; }
        public string CONTACT_NO_1 { get; set; }
        public string CONTACT_NO_2 { get; set; }
        public string CREATED_BY { get; set; }
        public System.DateTime CREATED_ON { get; set; }
        public string MODIFIED_BY { get; set; }
        public Nullable<System.DateTime> MODIFIED_ON { get; set; }
        public bool ACTIVE { get; set; }
        public System.Guid ROWGUID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_CUSTOMER_ADDRESS> tbl_CUSTOMER_ADDRESS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_SPARE_INVOICE> tbl_SPARE_INVOICE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_SPARE_SALE_ORDER> tbl_SPARE_SALE_ORDER { get; set; }
        public virtual tbl_CUSTOMER_TYPE tbl_CUSTOMER_TYPE { get; set; }
    }
}
