//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shop2StopDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_PERMISSION
    {
        public int OWNER_ID { get; set; }
        public int PERMISSION_ID { get; set; }
        public string PROCESS { get; set; }
        public Nullable<short> ROLE_ID { get; set; }
        public Nullable<byte> PERMISSION { get; set; }
        public System.Guid ROWGUID { get; set; }
    
        public virtual tbl_PROCESS tbl_PROCESS { get; set; }
        public virtual tbl_ROLE tbl_ROLE { get; set; }
    }
}
