//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Stop2ShopDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_SPARE_PART_LOC
    {
        public int OWNER_ID { get; set; }
        public int PART_LOC_ID { get; set; }
        public int SPARE_PART_ID { get; set; }
        public Nullable<int> LOCATION_ID { get; set; }
        public Nullable<decimal> SAFETY_STOCK { get; set; }
        public Nullable<short> RACK_ID { get; set; }
        public Nullable<short> BIN_ID { get; set; }
        public System.Guid ROWGUID { get; set; }
    
        public virtual tbl_BIN tbl_BIN { get; set; }
        public virtual tbl_RACK tbl_RACK { get; set; }
        public virtual tbl_SPARE_PART tbl_SPARE_PART { get; set; }
        public virtual tbl_STORAGE_LOC tbl_STORAGE_LOC { get; set; }
    }
}
