//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shop2StopDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_SPARE_INVOICE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_SPARE_INVOICE()
        {
            this.tbl_SPARE_INVOICE_PART = new HashSet<tbl_SPARE_INVOICE_PART>();
        }
    
        public int OWNER_ID { get; set; }
        public int SPARE_INV_ID { get; set; }
        public int SPARE_INV_NO { get; set; }
        public System.DateTime INVOICE_DATE { get; set; }
        public Nullable<byte> BILL_TYPE { get; set; }
        public Nullable<byte> INVOICE_TYPE { get; set; }
        public byte ORDER_TYPE { get; set; }
        public Nullable<int> LOCATION_ID { get; set; }
        public Nullable<int> CUSTOMER_ID { get; set; }
        public Nullable<int> PICK_SLIP_ID { get; set; }
        public Nullable<short> PAYMENT_MODE_ID { get; set; }
        public Nullable<decimal> INVOICE_VALUE { get; set; }
        public Nullable<decimal> DISCOUNT { get; set; }
        public Nullable<decimal> ROUND_OFF { get; set; }
        public Nullable<decimal> TOT_AMT_RECV { get; set; }
        public Nullable<byte> STATUS { get; set; }
        public bool ACTIVE { get; set; }
        public Nullable<int> CUSTOMER_PO_NO { get; set; }
        public Nullable<System.DateTime> CUSTOMER_PO_DATE { get; set; }
        public string CREATED_BY { get; set; }
        public System.DateTime CREATED_ON { get; set; }
        public string MODIFIED_BY { get; set; }
        public Nullable<System.DateTime> MODIFIED_ON { get; set; }
        public System.Guid ROWGUID { get; set; }
    
        public virtual tbl_CUSTOMER tbl_CUSTOMER { get; set; }
        public virtual tbl_PAYMENT_MODE tbl_PAYMENT_MODE { get; set; }
        public virtual tbl_PICK_SLIP tbl_PICK_SLIP { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_SPARE_INVOICE_PART> tbl_SPARE_INVOICE_PART { get; set; }
        public virtual tbl_STORAGE_LOC tbl_STORAGE_LOC { get; set; }
    }
}
