//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shop2StopDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_SPARE_PO_DET
    {
        public int OWNER_ID { get; set; }
        public int SPARE_PO_DET_ID { get; set; }
        public int SPARE_PO_ID { get; set; }
        public int SPARE_PART_ID { get; set; }
        public Nullable<decimal> ORDER_QTY { get; set; }
        public Nullable<decimal> PENDING_QTY { get; set; }
        public Nullable<decimal> IN_TRANS_QTY { get; set; }
        public Nullable<decimal> REJ_QTY { get; set; }
        public Nullable<decimal> RECV_QTY { get; set; }
        public Nullable<decimal> RATE { get; set; }
        public Nullable<decimal> TAX { get; set; }
        public Nullable<int> SEQ_NO { get; set; }
        public System.Guid ROWGUID { get; set; }
    
        public virtual tbl_SPARE_PO tbl_SPARE_PO { get; set; }
    }
}
