//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Stop2ShopDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_PICK_SLIP_SO
    {
        public int OWNER_ID { get; set; }
        public int PICK_SLIP_ID { get; set; }
        public int SALE_ORDER_ID { get; set; }
        public System.Guid ROWGUID { get; set; }
    
        public virtual tbl_PICK_SLIP tbl_PICK_SLIP { get; set; }
        public virtual tbl_SPARE_SALE_ORDER tbl_SPARE_SALE_ORDER { get; set; }
    }
}
