//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shop2StopDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_SPARE_COST
    {
        public int OWNER_ID { get; set; }
        public int SPARE_COST_ID { get; set; }
        public int SPARE_PART_ID { get; set; }
        public Nullable<short> VENDOR_ID { get; set; }
        public Nullable<decimal> INVOICE_PRICE { get; set; }
        public Nullable<System.DateTime> VALID_FROM { get; set; }
        public Nullable<decimal> DLR_PAID_TAX { get; set; }
        public Nullable<decimal> TVS_PAID_TAX { get; set; }
        public Nullable<decimal> PART_COST { get; set; }
        public string CREATED_BY { get; set; }
        public System.DateTime CREATED_ON { get; set; }
        public string MODIFIED_BY { get; set; }
        public Nullable<System.DateTime> MODIFIED_ON { get; set; }
        public bool ACTIVE { get; set; }
        public System.Guid ROWGUID { get; set; }
    
        public virtual tbl_SPARE_PART tbl_SPARE_PART { get; set; }
    }
}
