//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shop2StopDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_ID_TABLE
    {
        public short TABLE_ID { get; set; }
        public Nullable<int> END_RANGE { get; set; }
        public Nullable<int> START_RANGE { get; set; }
        public string TABLE_NAME { get; set; }
        public Nullable<int> CURRENT_ID { get; set; }
        public System.Guid ROWGUID { get; set; }
        public int OWNER_ID { get; set; }
    }
}
