//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shop2StopDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_STORAGE_LOC
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_STORAGE_LOC()
        {
            this.tbl_PART_MFR_LOC_RACK_BIN = new HashSet<tbl_PART_MFR_LOC_RACK_BIN>();
            this.tbl_RACK = new HashSet<tbl_RACK>();
            this.tbl_SPARE_INVOICE = new HashSet<tbl_SPARE_INVOICE>();
            this.tbl_SPARE_PART_LOC = new HashSet<tbl_SPARE_PART_LOC>();
            this.tbl_SPARE_SALE_ORDER = new HashSet<tbl_SPARE_SALE_ORDER>();
        }
    
        public int OWNER_ID { get; set; }
        public int LOCATION_ID { get; set; }
        public string DESCRIPTION { get; set; }
        public string ADDRESS { get; set; }
        public System.DateTime CREATED_ON { get; set; }
        public string MODIFIED_BY { get; set; }
        public Nullable<System.DateTime> MODIFIED_ON { get; set; }
        public bool ACTIVE { get; set; }
        public Nullable<bool> DEF_SALE_ORD_LOC { get; set; }
        public System.Guid ROWGUID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_PART_MFR_LOC_RACK_BIN> tbl_PART_MFR_LOC_RACK_BIN { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_RACK> tbl_RACK { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_SPARE_INVOICE> tbl_SPARE_INVOICE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_SPARE_PART_LOC> tbl_SPARE_PART_LOC { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_SPARE_SALE_ORDER> tbl_SPARE_SALE_ORDER { get; set; }
    }
}
