//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shop2StopDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_PICK_SLIP_PART
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_PICK_SLIP_PART()
        {
            this.tbl_PICK_SLIP_PART_DET = new HashSet<tbl_PICK_SLIP_PART_DET>();
        }
    
        public int OWNER_ID { get; set; }
        public int PICK_SLIP_PART_ID { get; set; }
        public int PICK_SLIP_ID { get; set; }
        public Nullable<int> SALE_ORDER_ID { get; set; }
        public Nullable<int> REF_CUST_PO_PART_ID { get; set; }
        public Nullable<int> SPARE_PART_ID { get; set; }
        public Nullable<decimal> UNIT_RATE { get; set; }
        public Nullable<decimal> QUANTITY { get; set; }
        public Nullable<decimal> MRP { get; set; }
        public System.Guid ROWGUID { get; set; }
    
        public virtual tbl_PICK_SLIP tbl_PICK_SLIP { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_PICK_SLIP_PART_DET> tbl_PICK_SLIP_PART_DET { get; set; }
        public virtual tbl_SPARE_SALE_ORDER tbl_SPARE_SALE_ORDER { get; set; }
    }
}
