//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Stop2ShopDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_SPARE_PO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_SPARE_PO()
        {
            this.tbl_SPARE_PO_DET = new HashSet<tbl_SPARE_PO_DET>();
        }
    
        public int OWNER_ID { get; set; }
        public int SPARE_PO_ID { get; set; }
        public int SPARE_PO_NO { get; set; }
        public System.DateTime PO_DATE { get; set; }
        public Nullable<short> VENDOR_ID { get; set; }
        public byte ORDER_TYPE { get; set; }
        public string REMARKS { get; set; }
        public byte STATUS { get; set; }
        public string SAP_SALE_ORDER_NO { get; set; }
        public Nullable<System.DateTime> SAP_SALE_ORD_DT { get; set; }
        public Nullable<decimal> TOT_VAL { get; set; }
        public bool ACTIVE { get; set; }
        public Nullable<System.DateTime> PO_CONFIRMED_DATE { get; set; }
        public string CREATED_BY { get; set; }
        public System.DateTime CREATED_ON { get; set; }
        public string MODIFIED_BY { get; set; }
        public Nullable<System.DateTime> MODIFIED_ON { get; set; }
        public System.Guid ROWGUID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_SPARE_PO_DET> tbl_SPARE_PO_DET { get; set; }
        public virtual tbl_VENDOR tbl_VENDOR { get; set; }
    }
}
