//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Stop2ShopDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_PROCESS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_PROCESS()
        {
            this.tbl_MENU = new HashSet<tbl_MENU>();
            this.tbl_PERMISSION = new HashSet<tbl_PERMISSION>();
        }
    
        public string PROCESS { get; set; }
        public string DESCRIPTION { get; set; }
        public Nullable<byte> GROUP_ID { get; set; }
        public bool PROCESS_TYPE { get; set; }
    
        public virtual tbl_GROUP tbl_GROUP { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_MENU> tbl_MENU { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_PERMISSION> tbl_PERMISSION { get; set; }
    }
}
