//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Stop2ShopDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_SPARE_INVOICE_PART
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_SPARE_INVOICE_PART()
        {
            this.tbl_SPARE_INV_PART_DET = new HashSet<tbl_SPARE_INV_PART_DET>();
        }
    
        public int OWNER_ID { get; set; }
        public int SPARE_INV_PART_ID { get; set; }
        public int SPARE_PART_ID { get; set; }
        public int SPARE_INV_ID { get; set; }
        public Nullable<int> SALE_ORDER_ID { get; set; }
        public Nullable<decimal> INVOICE_QTY { get; set; }
        public Nullable<decimal> UNIT_PRICE { get; set; }
        public Nullable<decimal> MANUAL_DISC { get; set; }
        public Nullable<decimal> TAX { get; set; }
        public Nullable<decimal> PART_COST { get; set; }
        public Nullable<decimal> MANUAL_DISCOUNT_PERCENT { get; set; }
        public System.Guid ROWGUID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_SPARE_INV_PART_DET> tbl_SPARE_INV_PART_DET { get; set; }
        public virtual tbl_SPARE_INVOICE tbl_SPARE_INVOICE { get; set; }
        public virtual tbl_SPARE_SALE_ORDER tbl_SPARE_SALE_ORDER { get; set; }
    }
}
