//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Stop2ShopDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_PART_MFR_LOC_RACK_BIN
    {
        public int OWNER_ID { get; set; }
        public int PART_RK_BN_ID { get; set; }
        public int SPARE_PART_ID { get; set; }
        public int LOCATION_ID { get; set; }
        public short RACK_ID { get; set; }
        public short BIN_ID { get; set; }
        public Nullable<decimal> FREE_QTY { get; set; }
        public Nullable<decimal> BLOCK_QTY { get; set; }
        public decimal PART_COST { get; set; }
        public Nullable<decimal> MRP { get; set; }
        public Nullable<decimal> TAX { get; set; }
        public bool TAXABLE { get; set; }
        public string CREATED_BY { get; set; }
        public System.DateTime CREATED_ON { get; set; }
        public string MODIFIED_BY { get; set; }
        public Nullable<System.DateTime> MODIFIED_ON { get; set; }
        public bool ACTIVE { get; set; }
        public Nullable<System.DateTime> STOCK_RECEIVED_DATE { get; set; }
        public System.Guid ROWGUID { get; set; }
    
        public virtual tbl_BIN tbl_BIN { get; set; }
        public virtual tbl_STORAGE_LOC tbl_STORAGE_LOC { get; set; }
        public virtual tbl_RACK tbl_RACK { get; set; }
    }
}
