//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Stop2ShopDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_SPARE_INV_PART_DET
    {
        public int OWNER_ID { get; set; }
        public int SPR_INV_PART_DET_ID { get; set; }
        public int SPARE_INV_PART_ID { get; set; }
        public Nullable<decimal> QUANTITY { get; set; }
        public Nullable<decimal> MRP { get; set; }
        public Nullable<int> PART_RK_BN_ID { get; set; }
        public System.Guid ROWGUID { get; set; }
    
        public virtual tbl_SPARE_INVOICE_PART tbl_SPARE_INVOICE_PART { get; set; }
    }
}
