//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Stop2ShopDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_USER_ROLE
    {
        public short ROLE_ID { get; set; }
        public string USER_PROFILE_ID { get; set; }
        public System.Guid ROWGUID { get; set; }
    
        public virtual tbl_ROLE tbl_ROLE { get; set; }
        public virtual tbl_USER tbl_USER { get; set; }
    }
}
